[formatter.cpp]
command = "astyle"
options = ["--style=mozilla", "-n"]
includes = [ "*.ino", "*.cpp", "*.hpp", "*.c", "*.h" ]
excludes = []

[formatter.markdown]
command = "mdformat"
includes = ["*.md"]

